apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "roar-db.name" . }}
  labels:
    app: {{ template "roar-db.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ template "roar-db.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "roar-db.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      {{- if .Values.image.pullPolicy }}
        imagePullPolicy: {{ toYaml .Values.image.pullPolicy }}
      {{- end }} 
        ports:
        - name: {{ .Values.deployment.ports.name }}
          containerPort: {{ .Values.deployment.ports.containerPort }}
        env:
          {{- include "roar-all.environment-values" . | indent 10 }}
       

