roar-web-container:
    image: quay.io/bclaster/roar-web:1.0.1
    ports:
        - "8089:8080"
    links:
        - "roar-db-container:mysql"
roar-db-container:
    image: quay.io/bclaster/roar-db:1.0.1
    ports:
        - "3308:3306"
    environment:
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_DATABASE: registry
        MYSQL_ROOT_PASSWORD: root+1
